name: Build and Run Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          envkey_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

      - name: Build Spring Boot JAR
        run: ./mvnw clean package

      - name: Build Docker image
        run: docker build -t project-app .

      - name: Stop and Delete old Container
        run: docker rm -f spring-boot
        
      - name: Run Docker container
        run: docker run -d --rm --name spring-boot -p 8080:8080 project-app
